### ISSUE TITLE
Misscaled gene model

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#114]
If only alignments are selected, the coverage is shown, but the gene model is not scaled correctly. Also, if only the alignments are uploaded, we should probably call variants by default.

**Comment by AlistairNWard** [comment]
Also, if we default to a trio, we should call on all bam files and so can still show the Prioritization matrix.

**Comment by AlistairNWard** [comment]
One other observation. If I select three BAM files and no VCF files, we see the coverage for all three (misscaled gene model). If I call with freebayes, I see that variants are called (e.g. the number), but no variants are actually displayed. This is observed on local and remote files.

**Comment by tonydisera** [comment]
Another great catch, Al.  I have fixed the coverage chart scaling problem when only bam file provided.  I still need to change gene.iobio to automatically call freebayes variants.

**Comment by tonydisera** [comment]
Oh yeah.  I was able to see the problem on the trio of alignments.  That is fixed now.  Also, when user clicks on 'call from alignments' link, all variant cards will have variants called.  The feature matrix will display and the inheritance mode will be determined.  Are you okay with going this route instead of automatically calling variants as discussed in yesterday's lab meeting?

**Comment by AlistairNWard** [comment]
Yep, that sounds great to me.
