### ISSUE TITLE
Include hom ref in allele count tool tips

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#121]
Instead of n/a for samples that do not have the variant, include the allele counts. This is only valid for multisample vcf files, but in that case, the genotype will be 0/0, but the allele counts are still provided. This would be very useful since it may be the case that the sample is called as a hom ref 0/0, but they do have some evidence for the alternate. With n/a listed, there is no way to determine this. We should see an almost empty box for this samples allele count.

**Comment by tonydisera** [comment]
It turns out that getting this right requires a non-trivial change to the app.  (Weird that something this trivial could trigger a big change, huh?)
The good news is that I have made recent app organization changes to make this possible.  And with the rework, multi-sample vcf access will be significantly faster for trios since the app will retreive the vcf records for all samples in one trip to the iobio services.

**Comment by tonydisera** [comment]
I figured out a simple workaround to get the hom ref counts on the mother and father.  Does this look ok?

<img width="365" alt="screen shot 2016-02-04 at 1 02 17 pm" src="https://cloud.githubusercontent.com/assets/8420103/12828192/893bedf0-cb40-11e5-9719-a981b52caad6.png">

**Comment by AlistairNWard** [comment]
Yes, this looks good.What do you mean when you say you'll hide the homrefs from the variant cards? Are they appearing as variant symbols? If so, agreed, we don't want hom-refs shown or included in counts of variants.

**Comment by tonydisera** [comment]
Yeah, the app has to keep those variants to show in the allele counts in the proband's tooltip, but we don't want to display or include them in the counts.
