### ISSUE TITLE
Gene ZAK is missing from gene list

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#155]

**Comment by tonydisera** [comment]
It looks like ZAK is under the gene name MLTK.   I guess that Gencode and RefSeq use this gene name instead of ZAK.  Is it okay to close this issue?
<img width="498" alt="screen shot 2016-01-03 at 7 17 38 pm" src="https://cloud.githubusercontent.com/assets/8420103/12082378/e2106362-b24e-11e5-8678-4ea85ca8de17.png">
<img width="1121" alt="screen shot 2016-01-03 at 7 18 15 pm" src="https://cloud.githubusercontent.com/assets/8420103/12082380/e7bee658-b24e-11e5-8128-de7464d4a23f.png">

**Comment by AlistairNWard** [comment]
We should probably talk to ARUP and try and determine if this is a common situation. I got the ZAK gene from ARUP. We could consider expanding the gene database to contain aliases, but if this is a rare care, I would be against it.

**Comment by AlistairNWard** [comment]
I've come across this a couple of times with different genes. I'm not sure that this is something we can elegantly deal with, so I'm going to close it.
