### ISSUE TITLE
Problem with ClinVar on RAI1

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#196]
The RAI1 use case has a variant marked as pathogenic in ClinVar. In the current version on nv-dev, the variant is no longer marked up as being in ClinVar. In addition, the HGVSc is enst00000353383.1:c.2273c>a, but the variant is a G->A SNP. Something odd is going on here.

**Comment by tonydisera** [comment]
I found the problem with the missing clinvar entries -- the clinvar requests are batched for 100 variant ids at a time.  I coded it to use round instead of ceiling, so it was missing the second batch of variant ids.
<img width="365" alt="screen shot 2016-02-02 at 9 44 33 pm" src="https://cloud.githubusercontent.com/assets/8420103/12773235/bc3fb04c-c9f6-11e5-80c6-7845fdd63a1d.png">

The HGVSc is correct when I test locally, but incorrect as you show on nv-dev.  So my guess is that a fix in the last week has addressed this issue.
<img width="242" alt="screen shot 2016-02-02 at 9 44 26 pm" src="https://cloud.githubusercontent.com/assets/8420103/12773233/b6d064d0-c9f6-11e5-9a72-9b936b132ee3.png">



I'm going to put a new gene.iobio out on nv-dev tonight since a number of bug fixes have be commited since the last deploy.
