### ISSUE TITLE
Inspect variant panel is only updated if open

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#217]
If the left panel is closed and a variant is selected, then the inspect variant panel is opened, it is blank. Now select a variant again and the info appears in the panel. Now closed out the left panel, select a new variant, reopen the left panel and it still showing the previously selected variant.

**Comment by tonydisera** [comment]
I can recreate this bug.  Thanks for the great information.  Here is what I propose:  let's get rid of the 'Inspect' link on the tooltip.  Instead, anytime you click on a variant or a ranked variant in the matrix, the left panel will open (if not already open) and switch to the Inspect card, showing the variant just clicked.

**Comment by AlistairNWard** [comment]
Yes, I totally agree with this.

**Comment by tonydisera** [comment]
I changed the tooltip logic so that whenever you click on a variant (or a column in the matrix), the left side panel will open (if not already open) and show the Inspect variant panel for the variant that was just selected.  So the tooltip no longer shows the 'Inspect' link since it will automatically occur when a variant is selected through the click event.

Because the side panel will open whenever a variant is clicked, it became critical to fix the re-positioning of the tooltip (as well as the rectangle around the variant) when the side panel is opened or closed.  This was fixed by listening for the side panel 'open' or 'close' event in the variant card and matrix panel to re-display the tooltip based on new coordinates.
