### ISSUE TITLE
Tour needs updating

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#236]
Number 6 is hidden behind the side buttons and refers to 'Learn more' which has been replaced.

**Comment by tonydisera** [comment]
good eye.  thanks.

**Comment by tonydisera** [comment]
See gene.iobio commit: 16689e3d11275012b812d39125ebfb38fdacdcbf [16689e3]

ix problems associated with switching between different app tours.
1. The basic problem was that the close event was occurring AFTER the open even in the case where the user clicks on one tour and then another (without closing the first). By getting rid of the animation to close the bottom page guide area, the sequence of events ensures that the new tour to be opened will stay opened.
2. Also had to use a different query selector for the phenolyzer button so that the main tour's step for pointing out the genes icon button isn't confused with the first step on the Phenolyzer tour.
3. I had to modify page guide to support multiple tours, so this change should probably be pushed to their repo.
