### ISSUE TITLE
Selected phenolyzer genes should show in same order as the rankings.

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#258]

**Comment by tonydisera** [comment]
The phenolyzer genes do appear in the correct order when they are first loaded into the gene buttons area.  However, if a phenolyzer gene is removed and then re-added, it goes to the end of the gene button list.

**Comment by AlistairNWard** [comment]
There are some peculiarities though. For lactic acidosis, PDHA1 always appeared first despite not being first in the list.

**Comment by tonydisera** [comment]
Yes, I can reproduce this.  I PDHA1 is already in the gene buttons before Phenolyzer is run, it stays in its current position.

**Comment by AlistairNWard** [comment]
I'll retest when CHPC is back up. But I believe that this still happens even if PDHA1 isn't initially selected.

**Comment by AlistairNWard** [comment]
Ok, so try this out. Open link:

http://gene.iobio.io/?rel0=proband&rel1=mother&rel2=father&name0=&vcf0=https://s3.amazonaws.com/iobio/gene/wgs_platinum/platinum-trio.vcf.gz&bam0=https://s3.amazonaws.com/iobio/gene/wgs_platinum/NA12878.bam&name1=&vcf1=https://s3.amazonaws.com/iobio/gene/wgs_platinum/platinum-trio.vcf.gz&bam1=https://s3.amazonaws.com/iobio/gene/wgs_platinum/NA12892.bam&name2=&vcf2=https://s3.amazonaws.com/iobio/gene/wgs_platinum/platinum-trio.vcf.gz&bam2=https://s3.amazonaws.com/iobio/gene/wgs_platinum/NA12891.bam&sample0=NA12878&sample1=NA12891&sample2=NA12892&genes=

Import the following bookmarks:

chr20   57581374        57581375        A       C       CTSZ
chr21   36042447        36042448        A       C       CLIC6
chr21   36042447        36042448        A       G       CLIC6
chr21   45649486        45649487        C       T       ICOSLG
chr21   47957354        47957355        A       C       DIP2A
chr22   16162489        16162490        G       A       AP000525.9
chr22   16353421        16353422        T       G       NF1P6
chr22   21481071        21481072        G       A       POM121L7
chr22   22385713        22385714        T       C       IGLV4-69
chr22   22385830        22385831        A       C       IGLV4-69
chr22   22385848        22385849        A       C       IGLV4-69
chr22   22385857        22385858        G       C       IGLV4-69
chr22   38051460        38051461        A       C       SH3BP1
chr22   39636870        39636876        TAAACA  T       PDGFB
chrX    19369470        19369471        G       T       PDHA1
chrX    100749022       100749023       A       G       ARMCX4
chrX    117973739       117973740       T       G       RP4-562J12.2
chrX    135067674       135067675       G       C       SLC9A6
chrX    153520556       153520557       A       T       TEX28
chrX    154721268       154721269       C       G       TMLHE
chr1    145363701       145363702       T       C       NBPF10
chr7    303066  303067  G       C       AC187652.1
chr13   100623451       100623452       T       G       ZIC5
chr14   20012688        20012689        C       T       POTEM
chr19   51171570        51171571        T       G       SHANK1
chrX    100749108       100749109       A       G       ARMCX4
chr6    27115123        27115127        GACA    G       HIST1H2AH
chr5    120021915       120021916       A       G       PRR16
chr10   128923870       128923871       T       TG      DOCK1
chr14   106691776       106691777       C       A       IGHV3-21
chr17   76471351        76471352        G       A       DNAH17
chr22   22385842        22385843        A       G       IGLV4-69
chr8    68062159        68062160        T       A       CSPP1
chr2    71170758        71170759        A       C       ATP6V1B1
chr22   31969062        31969063        A       G       SFI1
chr1    17302206        17302207        T       G       MFAP2

Ok, so a number of genes open up (of which PDHA1) is one and we are not in any gene ourselves. Now go to Genes and add lactic acidosis and hit Run. The top ten genes are now shown instead of the bookmarked genes as badges and TTPA (the top hit) is not selected, but highlighted. However, PHDA1 is number 1!

![screen shot 2016-03-16 at 12 51 31 pm](https://cloud.githubusercontent.com/assets/523111/13820925/ea15f120-eb75-11e5-835b-8c34dec99c9f.png)

**Comment by tonydisera** [comment]
Thank you for the beautiful reconstruction of events.  Yes, I am seeing the same problem.  I need to rework the way genes get sorted in the gene button list to take into account phenolyzer rank.   

Also, I'm wondering when the bookmarked gene list went away after the Phenolyzer run.  I thought that the logic was to add to the list, but not replace it.  What would you expect the app to do?

**Comment by AlistairNWard** [comment]
I think this was part of the design session that we never converged on an answer! What we probably want is logic to let the user decide. So they can choose to essentially a union, an intersection or just the individual lists. For now, I think it's fine to replace.

**Comment by AlistairNWard** [comment]
As an extension to this. If you then click on a gene badge, your Data button starts wiggling at me and no data is displayed, even though all the data is in the URL.

**Comment by AlistairNWard** [comment]
We also talked about a glyph or highlighting to indicate genes that contain a bookmarked variant. I guess we maybe need to make some decisions on this, but if we start going down the logic road, this is way more than can go in Release 2.1.

**Comment by tonydisera** [comment]
I have fixed the gene.iobio code in the following way:
1.  The rank order of the phenolyzer genes is always maintained.  If a gene button already is present and it is in the phenolyzer list, the gene button will be removed and added back so that it is always grouped with the phenolyzer genes. 

2.  Bookmarked genes are always shown with the bookmarked glyph.  Until we introduce rank into bookmarked variants, the phenolyzer rank trumps.  So if phenolyzer genes already exist and then bookmarks are imported, the phenolyzer gene button order is not disturbed.  Instead, in the case where a bookmarked gene is a phenolyzer gene, a bookmark glyph is added to the phenolyzer gene button.  So the gene button will have the blue border + the bookmark glyph.

3. If bookmarks are imported and then phenolyzer is run, the bookmarked gene button that is also a phenolyzer gene will be repositioned to maintain to the phenolyzer rank.

**Comment by AlistairNWard** [comment]
This sounds spot on. Once we think about ranked variants and ranked genes, we can worry about logic and user options.
