### ISSUE TITLE
False negative discovery - suggested variants

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#334]
Include suggested variants panels for selected databases and recall all these loci using Freebayes to see if there is any evidence that they might be present, or that there is 'good' evidence that they are not. The required evidence for a true negative should be user definable. Supersedes #154

**Comment by AlistairNWard** [comment]
We need to build a temporary vcf of the gene region containing all variants in the known variant database and then specify this file in Freebayes with the -@ argument. Then also set -l in freebayes to limit calling to the variants in the supplied vcf.

**Comment by tonydisera** [comment]
See Al's build of freebayes here:
/uufs/chpc.utah.edu/common/home/marth-d1/home/award/analysis/iobio/suggested_variants/freebayes/bin/freebayes

**Comment by tonydisera** [comment]
After Al and I discussed this feature, we decided that we won't allow the user to call variants with any control over runtime args since this complicated the UX.  Instead, the default behavior will be to call variants with the -@ argument, passing in the ClinVar variants so that less evidence is required to call variants for these known alleles.
