### ISSUE TITLE
Selecting a gene badge which is the prefix of another gene

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#359]
Run the demo data set and just add the following genes to the list. ADA,ADAM17,ADAR.

If you click on ADA, all three gene badges show as being analyzed. I don't think this is really the case, but all genes that start with ADA are visualized.

**Comment by tonydisera** [comment]
This should be fixed.  I also fixed the code so that if the search returns a big list, it can be scrolled.  It used to just stop at 20.  Also, the gene list is now sorted alphabetically.
<img width="231" alt="screenshot 2016-07-12 14 34 50" src="https://cloud.githubusercontent.com/assets/8420103/16782895/febaf604-483e-11e6-90a9-799cf4c3c8cf.png">
One thing that is a bit annoying with scrollbars in the browser is that they don't appear until you attempt to scroll.  Notice in the image above that there are no visible scrollbars.

**Comment by AlistairNWard** [comment]
I tried entering ACA and I get a lot of repeats.

**Comment by AlistairNWard** [comment]
![screen shot 2016-07-14 at 2 19 04 pm](https://cloud.githubusercontent.com/assets/523111/16850618/fbd5d27a-49cd-11e6-9c0f-15f8e0adafaf.png)

**Comment by tonydisera** [comment]
blame it on your fearless co-directory. :b  He is the one that populated the genes from gencode.   If the records are identical, I'll just add a unique index on gene name to the sqlite3 db.

**Comment by AlistairNWard** [comment]
I always blame @chmille4 and the blame is rarely misplaced!

**Comment by tonydisera** [comment]
I recreated the gene_names.json that is in the root directory of gene.iobio.  This gene list was generated by running an sql query to get all distinct gene names from the gene table.
The old gene_names.json had fewer gene names and of those, some were duplicates. The new gene_names.json now contains genes from both refseq + gencode.  One consequence of this is that some genes may not have transcripts in gencode or refseq.  So I will create another issue to sort this out.

Here are the stats:
new  gene_names.json  has  66,645 genes, all unique
old  gene_names.json had 57,820 genes,  w/o dups: 55,765 genes.
