### ISSUE TITLE
Only cache proband's variants so that ~200 genes can be analyzed.

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#362]
I am running two gene instances and both have a lot of genes. I've only analyzed 2 pages worth each, but have exceeded my local storage. I wonder if we are caching too much?

**Comment by tonydisera** [comment]
Yeah, perhaps we should only cache the trio variants when the proband has variants of possible interest. Try the new version of gene and click on clear cache.

**Comment by AlistairNWard** [comment]
When we complete this issue, make sure we consider caching of variants called with Freebayes.

**Comment by chmille4** [comment]
Just remembered that cache won't work on our cluster as is. Each minion instance has it's own cache so a cluster of minions will cause caching issues. There are a few solutions to this 

1. Create central cache service
2. Use the same trick we use for local files for returning an IP address to an instance so that  we will send cached requests to the appropriate instance.

Option 1 is probably better overall, but option 2 would be much easier to do.

**Comment by yiq** [comment]
Has anyone tried out the dynamodb backed cache store API  I made a few weeks ago?

**Comment by tonydisera** [comment]
Sorry Yi!  You can create servers faster than we can use them!  Power.  True power.

**Comment by AlistairNWard** [comment]
Would it be worth just building a database as we analyze all, that we store on the server. We can then just send filter queries at the database from there on.

**Comment by tonydisera** [comment]
Interesting.  We would need to tie the database to a user session.  The biggest advantage to this approach would be running sql queries on the analyzed data.  If we expand analysis to hundred/thousands of genes, this may be necessary.
