### ISSUE TITLE
All genes (union of gencode + refseq) should be available in gene search box.  In cases where gene belongs to only refseq or gencode, switch to that gene source.

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#379]
A new https://github.com/tonydisera/gene.iobio/issues/379gene_names.json was created to get all unique gene names from the sqlite3 gene.iobio.db database.  This resulted in a union of refseq and gencode names.  (See related issue #359).

The gene names need to contain the gene source so that the app can filter to only show genes from the selected gene source (gencode or refseq).  This will ensure that any selected gene has valid transcripts.

**Comment by tonydisera** [comment]
Fixed by creating new genes.json that is a combination of all refseq and gencode genes.  Each gene object has a name and a source field, which will be used to filter the list when the gene source changes.

**Comment by AlistairNWard** [comment]
I think we need  to handle the genes unique to gencode or refseq differently. The gene ABCA9-AS1 is only in the Gencode set. These are my observations:

1. If I am set to gencode, these gene will autocomplete and everything is good. If I then select Refseq, the gene is not found and the gene badge is removed from the top of the list.

2. If I am set to refseq, the gene will not autocomplete, so I think it isn't present.

I don't think either of these situations are ideal. If I'm specifically looking for one of these genes and am set to the wrong gene set, I'll think I can't analyze the gene which is untrue. And if I switch to the other set, I don't want it removed, since I was happily looking at it.

Maybe the solution is to allow autocomplete on the combined set, regardless of whether the gene is present in both sets. If you are set to the wrong set, when you select the gene, the error message could pop up to say that the gene isn't present in the present gene set and that you are automatically being switched. Then automatically switch. If you attempt to change the gene set to one where the gene isn't present, it won't let you and tells you why.

I have created a new json (attached) that include the 'gencode_unique' and 'refseq_unique' fields, so we can immediately tell if the gene is unique to one or other of the gene sets.

**Comment by AlistairNWard** [comment]
Can't attach a json. Emailed it.

**Comment by tonydisera** [comment]
This is one of many reasons why I love working with you! Thank you for thinking this through!

**Comment by tonydisera** [comment]
What should we do during 'Analyze all' if gene is not in current gene source?

**Comment by AlistairNWard** [comment]
Probably just analyze the source that is available. We would want to make it clear when you move to that gene that the analysis was performed on a different gene set though. This is a little tricky!

**Comment by tonydisera** [comment]
Hi Al.  I've taken care of it in the code, but would you mind re-running the script to get rid of duplicate records?  If this is a big deal, I can regenerate from the sqlite3 db.

**Comment by AlistairNWard** [comment]
No problem. For some reason, I just assumed there were no duplicates to begin with. I'll rerun now.

**Comment by tonydisera** [comment]
Yeah, the way the relational db is design is quirky.  (my fault.)  there is a gene row for each 'source'.

**Comment by AlistairNWard** [comment]
No problem, it's an easy script. I just added a couple of counters so when it's done, it'll tell me how many of each, so I can check that it tally's with your number above. Just hit go, so should be done momentarily...

**Comment by tonydisera** [comment]
Here's what the counts should be according to gene.iobio code:


unique genes  = 66645
gencode only = 26657
refseq only = 10880

**Comment by AlistairNWard** [comment]
Damn it - I was just writing out my numbers!

**Comment by AlistairNWard** [comment]
In both sets: 29107
Gencode unique: 26658
Refseq unique: 10880
Total: 66645

So I get a minor discrepancy! Some number of genes, but one more unique to gencode!

**Comment by tonydisera** [comment]
I'm getting +5000 refseq only genes without any transcripts.  How about this:  We keep these genes in the dropdown list for completeness, but we show an error symbol by the gene badge and indicate in the gene info area (where we show if it is a pseudogene, etc.) that this gene doesn't have any transcripts and therefore cannot be analyzed.

**Comment by tonydisera** [comment]
For testing - 
Gencode only - gene AC002429.5
RefSeq only - gene BLACAT1

**Comment by tonydisera** [comment]
IMPORTANT -  The use case of a refseq gene with no transcripts cannot be tested until a change to the geneinfo service is pushed by Yi to the latest stage (nv-green) build, which should be forthcoming when the samtools timeout problem is addressed.

**Comment by AlistairNWard** [comment]
I don't think this is working correctly yet. Try the following:

http://127.0.0.1:4000/?rel0=proband&rel1=mother&rel2=father&name0=NA19240&vcf0=https://s3.amazonaws.com/iobio/samples/vcf/exome-trio.vcf.gz&bam0=https://s3.amazonaws.com/iobio/samples/bam/NA19240.bam&sample0=NA19240&name1=NA19238&vcf1=https://s3.amazonaws.com/iobio/samples/vcf/exome-trio.vcf.gz&bam1=https://s3.amazonaws.com/iobio/samples/bam/NA19238.bam&sample1=NA19238&name2=NA19239&vcf2=https://s3.amazonaws.com/iobio/samples/vcf/exome-trio.vcf.gz&bam2=https://s3.amazonaws.com/iobio/samples/bam/NA19239.bam&sample2=NA19239&gene=RAI1&genes=RAI1,AIRE,MYLK2&rel=mother

1. Make sure Gencode is selected,
2. Type BLACAT1 in gene dropdown.
3. The warning that we're changing to Gencode appears, but very quickly disappears again, so you don't have time to read it. We see the gene model and the variants have gene model based predictions, but the gene badge has the no variants glyph.
4. Click the gene badge for BLACAT1 - now the glyphs appear in the gene badge and the warning that we changed to Gencode is present.

**Comment by AlistairNWard** [comment]
Fixed.
