### ISSUE TITLE
myGene2 initial version

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#397]

**Comment by tonydisera** [comment]
Based work off of educational addition.  Here are the changes needed for the simple view of gene.iobio for mygene2:

1. New sidebar
    -  Gene search  
   -  Gene panels (dropdown?  Who provides list?)
   -  Phenolyzer (labeled name of condition)
   - Go to Advanced mode (link)

2. Dropdown of genes instead of gene buttons

3. Show gene summary next to dropdown

4. Ranked variants - no symbols, just text:
       - Clinvar pathogenicity
       - Transcript ID
       - HGVS c (parse out transcript)
       -  HGVS p (parse out transcript)
       - Inheritance
       - Chr
       - Position
      - Ref
      - Alt
      - AF 1K
      - AF ExAC
     * Highlight column if clinvar path or likely path

5.  Annotating variants
     - Grab HGVS notations for all variants, not one at a time 
     - Get transcript that has highest impact on variant
     - Automatically filter out AF > 1% and non-pass filter

6.  No tooltip

7.  Show gene model (instead of gene box)

**Comment by tonydisera** [comment]
[mygene2_gene_iobio_pages.pdf](https://github.com/tonydisera/gene.iobio/files/441465/mygene2_gene_iobio_pages.pdf)

**Comment by tonydisera** [comment]
![geno_iobio_beginner_browser_mockup](https://cloud.githubusercontent.com/assets/8420103/18040042/5a732e98-6d66-11e6-9841-6b5318e7d9a3.png)

**Comment by tonydisera** [comment]
[1c99cb2]

**Comment by tonydisera** [comment]
Work in progress -
 1.  Need to show impact coloring in variants chart based on highest impact across all transcripts
 2. Need to wrap text
 3. FeatureMatrix separate cellSize into cellWidth, cellHeight
 4. FeatureMatrix - Background color red for pathogenic variant columns
 5. FeatureMatrix - n/a for non-coding variants ExAC AF

**Comment by tonydisera** [comment]
From Jessica and Mike:
Here are our thoughts:
First view should be left sidebar and then text below in the main panel ABOVE the genetic diagram view. Gene shown by default should be KDM1A.
Need a “Go to basic mode” button on the Advanced mode sidebar
Minimum font size in all places: 14px
Label above Gene search should be “Search for a gene (example: KDM1A)“
Label above Phenolyzer field should be “Search for a condition (examples: cystic fibrosis, breast cancer)
bug - if you click on a variant, it doesn’t highlight the corresponding column in the table
only show ClinVar-annotated variants below 1% frequency
Need to show canonical RefSeq transcripts and corresponding cDNA for canonical RefSeq transcript (otherwise it is not possible to turn the info in Gene.iobio into HGVS format, which is unfortunately what all the clinical labs are reporting)
change table row order (ClinVar, inheritance pattern, RefSeq transcript, cDNA, protein, chr, position, ref, alt, freq1K, freqExAC)
add legend to left sidebar (so it is visible all the time)
Legend contents:

blue = exons
(show triangle shape) = xxx
(show diamond shape) = xxx
(show square shape) = xxx
(show circle shape) = xxx
explain colors of variants

Text to show at top of main panel when first launching Gene.iobio. Also show this text in the left sidebar at all times so users can reference it.

**Comment by tonydisera** [comment]
Text to show at top of main panel when first launching Gene.iobio. Also show this text in the left sidebar at all times so users can reference it.

---------------------

Welcome to Gene.iobio on MyGene2

You can view your raw sequence data (VCF file) in multiple ways. In the left sidebar, you can search by name of gene (example: KDM1A) or by name of condition (examples: cystic fibrosis, breast cancer). When you search for the name of a condition, you may find a list of one or more genes reported to underlie that condition. 

In the main panel, you can see a dropdown menu with the name of each gene in your search results and to the right, a short summary of what is known about the gene.

Next you will see a cartoon drawing of the gene and its exons and introns.

Below that is a table of the variants you have in the gene. The table is sorted from left to right by whether the variant is predicted to underlie a condition according to a database called ClinVar (make ClinVar a link to: https://www.ncbi.nlm.nih.gov/clinvar/intro/). A person who has a variant does not necessarily have the condition. 

In Basic mode, only variants that have a classification in ClinVar and have a frequency of <1% in the general population are shown. If there are no matching variants, the table will be empty. You may have other variants in this gene that are not yet classified in ClinVar. These variants can only be seen in Advanced mode.

At the bottom of the main panel, you will see a cartoon drawing of the gene in each family member who has a VCF file available through MyGene2. Different types of variants are presented by different shapes (see legend in left sidebar for details). Hovering or clicking on a variant shape will highlight the corresponding column in the table.

**Comment by tonydisera** [comment]
On Sep 19, 2016, at 11:17 AM, Tony Di Sera <tony.disera@gmail.com> wrote:

Hi all,

Thanks for the review and comments.  These are great suggestions.  I should be able to get these changes out by the end of the week.  

I do have a few small questions/comments:



First view should be left sidebar and then text below in the main panel ABOVE the genetic diagram view. Gene shown by default should be KDM1A.
I will make this change to the Mygene2 gene.iobio ‘beginner’ app after it first launches, before the user has entered another gene name or a condition to search.  On a related note, do you want the separate ‘intro’ and ‘search’ pages before launching (as shown in your original mockup)?

No, we thought that this single revised page would replace these two pages. 



<mygene2_mockup.png>

only show ClinVar-annotated variants below 1% frequency

With this filter, most genes won’t show any variants.  In these cases, I propose we add a label to the middle ranked variants table indicating ‘No ClinVar annotated variants below 1% frequency found’.  Or perhaps the filter should be displayed in the left side panel at all times.

I think it would be useful to always return a result of some sort and in the page location consistently, even if the result is “No ClinVar variants <1% found.” This could be in either the side bar or the main body of the page. I think the latter is the more intuitive place for a user to expect them.

Need to show canonical RefSeq transcripts and corresponding cDNA for canonical RefSeq transcript (otherwise it is not possible to turn the info in Gene.iobio into HGVS format, which is unfortunately what all the clinical labs are reporting)

If the app annotates and filter based on the the canonical transcript, we could try putting transcript name next to the gene in the top panel and omitting it from the ranked variants table.  Otherwise, it will repeat the same transcript id in every cell.

**Comment by tonydisera** [comment]
To do (Jessica Chong's feedback):

- if synonymous variant, maybe it should show "p.(=)" instead of just a blank in the Protein field 

- Perhaps show Ranked variants panel with a message (No clinvar variants under 1% population frequency found).

**Comment by tonydisera** [comment]
Additional feedback - 

From Jessica -
By the way, I'm thinking it may be helpful to somehow flag the gene
list dropdown so that users know to look there for gene results after
the Phenolyzer run completes. Otherwise it's not at all clear that I
should click on the dropdown to see more genes
