### ISSUE TITLE
Export VCF based on genes shown in gene.iobio

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#413]

**Comment by tonydisera** [comment]
Here are the comments from the team on the highest priority features for saving data:

Matt:
If we had to pick one output to start with I'd say an Excel spreadsheet with relevant annotations for all bookmarked variants would be most helpful. This is mainly based on my conversations with people. Second one to build in would be an annotated VCF. 

We can definitely clarify what we want when we're all together this week. But those are my quick thoughts.

Alistair:
I would say the first things to work on would be an Excel output of bookmarked variants and a vcf of the bookmarked variants with the annotations from VEP, clinVar and AF in the INFO field. I would think that we just include bookmarked variants for now. We can have a meeting later this week while we're all together to decide what to do about the report.

If we can consume the annotated vcf, that would be good. I think we need to build in functionality to parse the INFO field for gene.iobio and probably vcf.iobio as well, so developing this module would be useful across the board

**Comment by AlistairNWard** [comment]
The output VCF file contains spaces in the IOBIO entry. I think these appear if the key has no value. For example "freebayesCalled# |" where there are no called variants, and so there is a space after the "#" and before the "|". Technically, this is ok as far as the vcf v4.3 spec is concerned, but whitespace was expressly forbidden in previous specs.

In order to give an iobio output vcf the best chance of being compatible with all common tools in use, I would vote to remove this whitespace.

**Comment by tonydisera** [comment]
Thank you for your detailed review and testing, Al!  Would it be spec-compatible if a '.' is used as the placeholder for a blank entry?

**Comment by AlistairNWard** [comment]
Yes, '.' would work.

**Comment by AlistairNWard** [comment]
Fixed.
