### ISSUE TITLE
Change gene badge page resets ordering

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#437]
Run, e.g. demo exome on all ACMG56 genes. Do not view all! Reorder on relevance. Now go to page 2 and back to page 1. Ordering has been reset.

**Comment by nielsonphu** [comment]
Failing selenium test has been written.

**Comment by tonydisera** [comment]
Awesome!

**Comment by nielsonphu** [comment]
Branch: issue_437
Pull Request: https://github.com/tonydisera/gene.iobio/pull/448

**Comment by tonydisera** [comment]
Hi Nielson.  So is the bug fix + the test written?  I just wanted to make sure since the issue is in the 'ready to validate' column.
Thanks!
Tony

**Comment by nielsonphu** [comment]
Yes, both are written although I didn't include the test in this branch since all the tests are in the "tests" branch. What I'll do is cherry-pick the test over to this branch since it makes more sense to have them together. In the meantime, you're free to review the code changes I made to see if I broke anything.

**Comment by nielsonphu** [comment]
This is ready to validate. Merged in the test and it now passes with my fix. To run the test yourself, run the following command from the project directory:

gulp e2e --test e2e/spec/gene_badges/paginating_should_not_change_order_spec.js -e chrome
