### ISSUE TITLE
Apply filters across genes so that gene badges change.

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#461]

**Comment by AlistairNWard** [comment]
I'm seeing problems with the filtering. Example:

1. Open new gene with demo data.
2. Apply known causative filter. 
3. Analyze all -> No glyphs in the badges (correct).
4. "Clear all" filters -> Still no glyphs appear in the badges (incorrect).
5. If I click on a gene badge, glyphs return.
6. Now apply "Known causative" filter -> all glyphs remain.

When I click on MYLK2 above it takes a while as though the data isn't cached. By selecting "Known causative" before analyzing all, do only the variants passing those filters get cached, rather than all variants?

**Comment by tonydisera** [comment]
Weird.  The badges come back (step #4) after I clear the filters.  What is going on?  What does that double rainbow mean?

**Comment by AlistairNWard** [comment]
Sorry - I'm still seeing this one. In fact, setting filters is not changing glyphs at all.

**Comment by AlistairNWard** [comment]
<img width="1161" alt="screen shot 2017-01-20 at 6 01 16 pm" src="https://cloud.githubusercontent.com/assets/523111/22168435/9661914c-df3a-11e6-9f3e-0b6fc3062819.png">

**Comment by tonydisera** [comment]
Interesting.  There is probably more silent errors going on.  Would you mind copy/pasting your console log?

**Comment by AlistairNWard** [comment]
Ok, there is an update not occurring here. Follow the steps mentioned above. When I apply the "known causative" filter, I see "0 of 1" (unless I press this too quickly while the 1 gene is being analyzed - then I see "0 of 0", even when analysis completes). 

Now analyze all. 3 genes are analyzed, 0 pass filters, but next to the "known causative" box, I still see "0 of 1". If I click the "known causative" box, it updates to "0 of 3".

**Comment by AlistairNWard** [comment]
I think a couple of my comments, including this one, are related to #513.

**Comment by AlistairNWard** [comment]
Also, we should update all of these counts when new data is added. I just changed all the links to the exomized platinum data, and the counts next to the filters remain.
