### ISSUE TITLE
Variants not loaded if vcf file entered after variants are called

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#535]
1. Open gene.iobio.
2. Enter BRAF.
3. Enter the BAM:

https://s3.amazonaws.com/iobio/samples/test_files/Horizon-HD728_Panel1385_Hyb11_HFW2KBBXX.bam

4. Load. Yes to call variants.
5. Add in the vcf:

https://s3.amazonaws.com/iobio/samples/test_files/Horizon-HD728_Panel1385_Hyb11_HFW2KBBXX.union.vcf.gz

Only the called variants are shown. Even though I now have a vcf file specified, no variants are being pulled from it.

**Comment by tonydisera** [comment]
This was a good one!  I'm glad you noticed this problem.

Now, when the user re-enters the 'Select data' dialog and presses 'Load', all gene annotations will be cleared out because the genome build could have changed.  By fixing this bug, this issue was also fixed.  However, there is one caveat.  If alignments are loaded and variants are called and then the vcf URL/file is entered in the 'Select data' dialog, the called variants will get cleared out.  At this point, the user will have to go through 'Call variants' to see any 'new' variants.

**Comment by AlistairNWard** [comment]
I think that's fine. This is not going to be a common route to analysis, I don't imagine.
