### ISSUE TITLE
HGSV codes are inconsistent

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#583]
Using data:

https://s3.amazonaws.com/iobio/samples/test_files/Horizon-HD728_Panel1385_Hyb11_HFW2KBBXX.union.vcf.gz

https://s3.amazonaws.com/iobio/samples/test_files/Horizon-HD728_Panel1385_Hyb11_HFW2KBBXX.bam

Click on the first variant (a ClinVar pathogenic variant). The full tooltip has no HGSVp or HGSVc codes. In fact none of the variants do.

Now choose the variant from the proband track and the HGSV codes now appear. Go back an pick the variant from the table and the codes are now there.

**Comment by tonydisera** [comment]
The HGVS notations slow down VEP annotation considerably, so these are pulled in 'on demand'.   It takes a couple of seconds for the HGVS notations to be filled in.  We have a couple of options here.  A quick fix would be to add 'accessing...' to the notations in the tooltip until they are filled in so that it is more apparent that the notations have yet to be retrieved.  Another approach would be to annotate the HGVS notations when VEP is run against all variants in the gene.  This perhaps could be a setting or site configurable.

**Comment by AlistairNWard** [comment]
The quick fix would probably work for now. If it takes a while, it probably doesn't make sense to force it on all variants, but when you select a variant, knowing to wait would be invaluable!

**Comment by tonydisera** [comment]
Great.  I've made this fix so that the HGVS fields show the 'loading' gif until the values are filled in.
