### ISSUE TITLE
Filtering variant selectors

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#604]
In the Filter panel, there are check boxes for Loaded and Called variants. What do these do? As far as I can tell, they don't do anything.

**Comment by mvelinder** [comment]
The logic was to be able to apply your filters only to loaded or called variants. As far as the "not doing anything" problem... I'd agree. They don't appear to be working as expected. Here's what I did to get them to work as expected (or how I'm guessing we want them to behave):

load gene.iobio.io
click try it with demo data
click analyze all genes
click call variants > for all genes
click filter to open filter panel
uncheck loaded variants -- everything but called denovo in MYLK2 should go away

The problem seems to be if you apply a filter THEN uncheck a loaded or called variants box -- which results in nothing happening. This can be reproduced by clearing all filters with the clear all button. Then applying the known causative filter and unchecking the loaded variants box... nothing will change. However, if you clear all filters again, uncheck loaded variants, THEN apply a filter things will change.

Other people seeing the same behavior?

**Comment by AlistairNWard** [comment]
Yes, you're right Matt. The order matters.  I vote that we just get rid of the check boxes. Since the called and loaded are delineated anyway, there is no reason to select or deselect them.

**Comment by tonydisera** [comment]
Yep, I can reproduce the problem.  Thank you for the great description.  I see a null reference error in the console messages so I should be able to fix this problem in the next 5 mins.  I'll push to production as soon as I have a fix.

**Comment by tonydisera** [comment]
Fixed.

**Comment by tonydisera** [comment]
I've been thinking we should get rid of the checkboxes 'Called' and 'Loaded' in the filter panel, too.  Now that we have the progress bar and the counts next to standard filters, along with the 'Called variant' glyph in the gene button, it seems like these checkboxes are not necessary.  

Are you guys ok with removing these?

**Comment by AlistairNWard** [comment]
Actually, my comment above was that I vote to get rid of the check boxes, so I'm definitely on board.

**Comment by tonydisera** [comment]
Fixed.  I've also done a bit of re-arranging on the Filter panel.  The VCF filter status has been moved up beside Inheritance mode to make it more prominent.  The ClinVar filters are now spread across t3 columns to free up a bit of vertical space.  The VEP Consequences now show up in one column and represent all values encountered so far during analysis instead of only the values for the currently selected gene.

Please validate on nv-dev-new.iobio.io and then I will push to production tomorrow.

**Comment by AlistairNWard** [comment]
Looks good to me. Maybe it's my eye, but has the "Clear all" button got uncentred again?

**Comment by tonydisera** [comment]
Yep.  It must be the new width for the warning glyph.  Good eye, mate.
