### ISSUE TITLE
Reloading bookmarks

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#615]
I am trying to clarify exactly what Steve means, but this was his comment, "So—I have a VCF with multiple trios.  Each time I want to look at a bookmarked variant, I have to go through the process of finding the trios in the VCF. 
It would be really great to have the ability to link individuals to the bookmarked variants so I don’t have to select the trio every time I want to look at them."

**Comment by tonydisera** [comment]
My guess is that he would like to tie the bookmarks to the gene.iobio URL that has all of the data files and samples specified.  Right now, since the bookmarks are saved in a file, it is 'detached' from the vcf files and sample ids.  Yi and Chase suggested that we store the bookmarked variants in dynamo db or S3 so that a link to the bookmarks could be included in the URL.   Of course, once we have the Project/Data layer, this won't be necessary.  But in the meantime, we may want to consider saving the bookmarks so that they can be retrieved via a URL or a token.

**Comment by AlistairNWard** [comment]
I actually think he's just asking for a GNomEx that works! My suspicion is that he's just adding files manually using the "Files" dialogue and not going through GNomEx, so even if the bookmarks are in the URL, he still needs somewhere to generate the URL. I asked him to clarify. Ultimately, I'm hoping that this will add institutional support for a GNomEx replacement.

**Comment by AlistairNWard** [comment]
I'm going to close this. Ultimately we can store data in hub, but in the meantime, a user can save bookmarks and reupload. This is sufficient until a general solution is available.
