### ISSUE TITLE
Inheritance mode is recessive on homozygous variant where variant is not present in mother or father.

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#63]
Inheritance mode can only be recessive if variant is present in one parent and not in another.  I think that the logic is getting messed up because the proband's variant is homozygous.  If the proband's variant where heterozygous, the inheritance mode would have been set to 'de novo'.

**Comment by tonydisera** [comment]
<img width="727" alt="screen shot 2015-07-05 at 6 56 07 pm" src="https://cloud.githubusercontent.com/assets/8420103/8514266/73dc54fe-2348-11e5-8fbc-0ba6a9a074d6.png">

**Comment by AlistairNWard** [comment]
This should still be listed as a de novo variant since it has arisen only in the proband. We may want to think about additional flagging in this instance though. The chances that both chromosomes independently have the same mutation is vanishingly small. This suggests that there is something else going on (e.g. lack of coverage or miscall in the parents etc).

**Comment by AlistairNWard** [comment]
I just looked at this variant with the standard inputs and I see it as recessive, but it is a het in both parents.

**Comment by tonydisera** [comment]
Thanks for checking this, Al.  Yeah, I'm seeing the same: parents are het, proband is hom.  I'm not sure what kind of state data cards were in when I saw this inconsistency.
