### ISSUE TITLE
In Files dialog, don't show affected sibs if proband vcf not entered

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/gene.iobio#644]
It is confusing to show affected/unaffected sibs when only alignments provided.

**Comment by AlistairNWard** [comment]
Why is this the case? If you don't give a vcf, variants are still called, so it still makes sense to see the affected/unaffected sibs, or am I misunderstanding?

If I am, then when you clear the proband vcf, the affected/unaffected sibs boxes should disappear.

**Comment by tonydisera** [comment]
The app only supports analyzing affected/unaffected sibs when a multi-sample VCF is provided for the proband.  The app doesn't support calling variants on affected/unaffected sibs (using BAM files).

I agree that the affected/unaffected sibs should clear selected values when the proband vcf is cleared.  However, it seems fine to show the dropdowns (with an empty selection).

**Comment by AlistairNWard** [comment]
I only suggested removing the drop down since it only appears if you add a proband vcf. So if you remove the proband vcf, it seemed symmetrical to remove the drop down.

Perhaps we should make this clear somehow. It wasn't obvious to me why I couldn't select sibs. What if all samples have individual vcf files? The user would expect to be able to select them, so would need an explanation of why they couldn't.

**Comment by tonydisera** [comment]
I see.  I agree.  When the Proband VCF is cleared, the sibs dropdowns should go away and only re-appear if the Proband VCF selection is for a multi-sample VCF.
