### ISSUE TITLE
Reported vs computed coverage

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/gene.iobio#77]
Do we need an explanation somewhere to describe the difference between these values? It may not be obvious to all users.

**Comment by tonydisera** [comment]
For the Platinum vcf (NA12878), the depth was always very close to the base coverage returned from samtools mpileup for the variant positions.  Interestingly, the vcf depth was usually a bit higher than the one determined from the alignments (samtools mpileup).  

Given that the tooltip is already large and there is only slight difference in the coverage reported in the vcf vs. determined from the alignments, it seems best to only show one coverage in the tooltip.  So, ff the bam file is loaded, the tooltip will show the coverage determined in realtime from samtools mpileup; otherwise the tooltip will show the depth reported in the vcf.
